/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.corposense.ocr.demo;

import ratpack.server.RatpackServer;

public class App {

    final public static int CONSTANT_VALUE = 1;

    public static void main(String... args) throws Exception {
        RatpackServer.start(server -> server
                .handlers(chain -> chain
                        .get(ctx -> ctx.render("Hello World!"))
                        .get(":name", ctx -> ctx.render("Hello " +
                                ctx.getPathTokens().get("name") + "!"))
                )
        );
    }

}
