/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.corposense.ocr.demo;


import ratpack.guice.Guice;
import ratpack.server.BaseDir;
import ratpack.server.RatpackServer;
import ratpack.thymeleaf3.ThymeleafModule;
import static ratpack.thymeleaf3.Template.thymeleafTemplate;


public class App {

    final public static int CONSTANT_VALUE = 1;

    public static void main(String... args) throws Exception {

        RatpackServer.start(server -> server
          .serverConfig( s -> s.baseDir(BaseDir.find()))
          .registry(Guice.registry(bindingsSpec -> bindingsSpec.module(ThymeleafModule.class)))
          .handlers(chain -> chain
                        .get(ctx -> ctx.render("Go to Upload file page"))
                        .get("upload", ctx -> ctx.render(thymeleafTemplate("upload")))
                        .post("ocr", ctx -> ctx.render(thymeleafTemplate("ocr")))
                        .get(":name", ctx -> ctx.render("Hello " +
                                ctx.getPathTokens().get("name") + "!"))
                )
        );




    }


}
